# удаление столбцов с большим количеством пропусков 
## (более 90%)

In [8]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('Diamond Price Prediction.csv')
df.head(10)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
9,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39

In [27]:
df['X'] = np.nan
df

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth),X
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,NaN
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,NaN
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,NaN
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,NaN
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,NaN
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,NaN
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,NaN
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,NaN
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,NaN
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,NaN

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Carat(Weight of Daimond)  53940 non-null  float64
 1   Cut(Quality)              53940 non-null  object
 2   Color                     53940 non-null  object
 3   Clarity                   53940 non-null  object
 4   Depth                     53940 non-null  float64
 5   Table                     53940 non-null  float64
 6   Price(in US dollars)      53940 non-null  int64
 7   X(length)                 53940 non-null  float64
 8   Y(width)                  53940 non-null  float64
 9   Z(Depth)                  53940 non-null  float64
 10  X                         0 non-null      float64
dtypes: float64(7), int64(1), object(3)
memory usage: 4.5+ MB

In [29]:
many_null_colms = [col for col in df.columns if df[col].isnull().sum() / df.shape[0] > 0.9]
df = df.drop(many_null_colms, axis=1)

In [30]:
df

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

## кодировка пропусков

In [45]:
df['Y'] = np.nan
df

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth),Y
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,NaN
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,NaN
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,NaN
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,NaN
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,NaN
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,NaN
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,NaN
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,NaN
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,NaN
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,NaN

In [46]:
df['Y'].value_counts(dropna=False)

NaN    53940
Name: Y, dtype: int64

In [47]:
df['Y'] = df['Y'].fillna(-9999)

In [48]:
df

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth),Y
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,-9999.0
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,-9999.0
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,-9999.0
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,-9999.0
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,-9999.0
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,-9999.0
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,-9999.0
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,-9999.0
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,-9999.0

# замена пропусков медианой всех значений

In [49]:
df["Y"] = df["Y"].fillna(df['Y'].median())

In [50]:
df

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth),Y
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,-9999.0
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,-9999.0
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,-9999.0
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,-9999.0
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,-9999.0
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,-9999.0
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,-9999.0
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,-9999.0
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,-9999.0
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,-9999.0